### ISSUE TITLE
Can it be used for Android app

### ISSUE THREAD

**Issue by Sandy4321** [kevalmorabia97/Chat-Messela-Blockchain-Messenger#4]
Can it be used for Android app
If not can you share similar project for Android app

**Comment by kevalmorabia97** [comment]
We haven't tried it with an Android app.

**Comment by Sandy4321** [comment]
Do you know another GitHub project for blockchain messenger suitable for Android or iOS App?
Or exactly blockchain messenger  Android or iOS app

**Comment by kevalmorabia97** [comment]
I don't have much experience with Android or iOS app development.
